spring.application.name=BidNow

#spring.datasource.url=
spring.output.ansi.enabled=ALWAYS

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver

#Postgre Sql DB confs

#spring.datasource.url=jdbc:postgresql://localhost:5432/auctiondb
#spring.datasource.username=app_user
#spring.datasource.password=app_password

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


spring.devtools.restart.enabled=false

# Wait for entities to make tables before excecuting data.sql
# spring.jpa.defer-datasource-initialization=true

debug=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587

#spring.mail.username=bidnowapp@gmail.com
#spring.mail.password=noco woda uiii nqod

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# Cloudflare R2 config

cloudflare.r2.account-id=d7059e16b82095ca47d810e8444f49f6




#cloudflare.r2.access-key-id=65c81805bf30efb8f6914a7641147469
#cloudflare.r2.secret-access-key=7ae5029e6179be13f3646162554809225d4a60a79e67edbbe927deaabb78492d
cloudflare.r2.access-key-id=${R2_ACCESS_KEY_ID}
cloudflare.r2.secret-access-key=${R2_SECRET_ACCESS_KEY}
cloudflare.r2.bucket=bidnow-testing-images
cloudflare.r2.endpoint=https://d7059e16b82095ca47d810e8444f49f6.r2.cloudflarestorage.com


cloudflare.r2.public-base-url=https://pub-6cd4fca3122d4e93bf79326e6762f99e.r2.dev/





#spring.task.scheduling.enabled=false
spring.task.scheduling.time-zone=Europe/Nicosia
