package com.example.webapp.BidNow.Enums;

public enum Endpoint {
    APPROVE,
    CREATE_CATEGORY, UPDATE_CATEGORY, DELETE_CATEGORY, CREATE_REFERRAL_CODE, EDIT_REFERRAL_CODE, ADMIN_UPDATE_USER, SEND_MESSAGE, GET_AUCTIONS, GET_AUCTION, CREATE_AUCTION, GET_MY_ACTIVE_BID_AUCTIONS, GET_MY_WON_AUCTIONS,USER_SIGNUP, USER_UPDATE_USERNAME, USER_UPDATE_AVATAR, USER_UPDATE_LOCATION, PLACE_BID, ADD_IMAGES, USE_REFERRAL_CODE, USER_SIGNIN,
    USER_UPDATE_ROLE, GET_MY_PENDING_AUCTIONS, GET_MY_AUCTIONS, CANCEL_AUCTION;
}
